from .basket import *
from .first_menu import *
from .filling_name import *
from .service import *
from .shop import *
from .payment import *
from .admin_cp import *
from .checker_cp import *
from .lottery import *
